### ISSUE TITLE
Generate rev with version substituted 

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-community/nurl#2]
It would be nice to get ``rev = "v${version}";`` with an option.

**Comment by figsoda** [comment]
what do you think of a `--overwrite` flag that changes the final output without being considered when calculating the hash
something like this:
- `--overwrite rev '"v${version}"'`
- `--overwrite repo pname`

**Comment by SuperSandro2000** [comment]
That sounds like a good idea

**Comment by figsoda** [comment]
added in https://github.com/nix-community/nurl/commit/6dc540c192380d9fc321c1bc96eed1ef533d1a08

**Comment by figsoda** [comment]
published in [0.3.0](https://github.com/nix-community/nurl/blob/v0.3.0/CHANGELOG.md#v030---2023-01-02)
