### ISSUE TITLE
FetchGitHub with submodules

### ISSUE THREAD

**Issue by dev-null-undefined** [nix-community/nurl#9]
When using this tool to update package that is using fetchFromGitHub with fetchSubmodules set to true.
The hash would mismatch since this tool is probably not fetching the submodules.
`nurl https://github.com/WerWolv/ImHex-Patterns ImHex-v1.26.2`

It would be nice if there was option for `nurl` to fetch with submodules maybe with command line flag?

**Comment by figsoda** [comment]
currently you can do `nurl https://github.com/WerWolv/ImHex-Patterns ImHex-v1.26.2 -a fetchSubmodules true`

I am planning to add a `--submodules` flag based on the git fetcher which will be faster, but I am running into issues with https://github.com/NixOS/nix/issues/5291

**Comment by dev-null-undefined** [comment]
Glad to hear that, yes adding that flag does solve my issue.
Thanks.

**Comment by figsoda** [comment]
`--submodules` has been implemented on main
